"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var linkedlist_1 = require("./linkedlist");
var list = new linkedlist_1.LinkedList();
list.append("dog");
list.append("cat");
list.append("parrot");
list.append("hamster");
list.append("snake");
list.append("turtle");
console.log(list.toString());
